const SELECCIONAR_CLIENTE = "SELECCIONAR_CLIENTE";
const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO";
const CANTIDAD_PRODUCTOS = "CANTIDAD_PRODUCTOS";
const VERIFICAR_CLIENTES = "VERIFICAR_CLIENTES";
const ACTUALIZAR_TOTAL = "ACTUALIZAR_TOTAL";

export {
  SELECCIONAR_CLIENTE,
  SELECCIONAR_PRODUCTO,
  CANTIDAD_PRODUCTOS,
  VERIFICAR_CLIENTES,
  ACTUALIZAR_TOTAL,
};
